### ISSUE TITLE
Cannot declare public holiday

### ISSUE THREAD

**Issue by zamach132** [InfotelGLPI/activity#11]
Hi, there is no way to declare public holiday. 
Every user, SuperAdmin included, can declare only private holiday. How to declare public holiday ?
Thanks for any sugestions.

**Comment by gguib** [comment]
Hi, have you tried in menu Setup --> Dropdowns --> Close times?

**Comment by zamach132** [comment]
Yes I have. 
But stil i can plan externalevents on closeties.

**Comment by gguib** [comment]
Do you mean add externalevents on public holiday ? No, you can't. 

![image](https://user-images.githubusercontent.com/56250594/97276150-1df81e80-1837-11eb-8666-edf1439188f6.png)

**Comment by zamach132** [comment]
I declared public holiday in dropdown -> colse time but nothing happend. 

![2020-10-27](https://user-images.githubusercontent.com/62652551/97278240-d1621280-1839-11eb-9e94-14b0eb223c09.png)
![2020-10-27 (1)](https://user-images.githubusercontent.com/62652551/97278257-d7f08a00-1839-11eb-8945-b625d4053b8c.png)

**Comment by gguib** [comment]
Maybe a cache problem, can you cache empty and disconnect / reconnect to see change ?

**Comment by zamach132** [comment]
Do you mean browser or server cache?

**Comment by gguib** [comment]
try both

**Comment by zamach132** [comment]
Ok, for browser cache i just used different browser. But i dont know how to clean server cache. Can You help ?

**Comment by gguib** [comment]
if you're on linux system  :

rm -R /var/www/glpi/files/_cache/* 
just try to locate _cache directory and delete all inside but not himself.

**Comment by zamach132** [comment]
Now I've got this

Warning: Cannot write "/var/www/html/glpi/files/_cache/glpi_cache_db_9.5.1.json" cache footprint file. Cache performance can be lowered. in /var/www/html/glpi/inc/cache/simplecache.class.php on line 273

Warning: Cannot write "/var/www/html/glpi/files/_cache/glpi_cache_db_9.5.16641aebaf1ca5eb4f70b17d094a4e1f9.json" cache footprint file. Cache performance can be lowered. in /var/www/html/glpi/inc/cache/simplecache.class.php on line 273

**Comment by gguib** [comment]
i think you've got problem right on _cache folder, try to fix it before.

**Comment by zamach132** [comment]
Ok, That was a premision issue. I fixed it. Everything is 777. But still no public holiday.

**Comment by zamach132** [comment]
I also have tried it on fresh instance, and it doesn't display public holiday as well.

**Comment by zamach132** [comment]
![obraz](https://user-images.githubusercontent.com/62652551/97281735-243dc900-183e-11eb-8b74-3893dc004dc6.png)
![obraz](https://user-images.githubusercontent.com/62652551/97281776-31f34e80-183e-11eb-8ca5-b21c2282ee53.png)

**Comment by gguib** [comment]
i think you forgot to create calendar and associate closetimes to it.

![image](https://user-images.githubusercontent.com/56250594/97332257-9207e600-187a-11eb-9645-399466f392af.png)

**Comment by zamach132** [comment]
As You can see it is asigned propertly. 

![obraz](https://user-images.githubusercontent.com/62652551/97332682-05a9f300-187b-11eb-9b53-e42e85cfccf7.png)

**Comment by zamach132** [comment]
But Your sugestion pushed me to chceck one more thing and i have founded problem. I had asigned wrog type of callendar - that was isue 

 - Wrong setting
![obraz](https://user-images.githubusercontent.com/62652551/97333230-9c76af80-187b-11eb-829f-8fbc28dee564.png)

- Good setting
![obraz](https://user-images.githubusercontent.com/62652551/97333326-c0d28c00-187b-11eb-9583-1f8cdd661c76.png)


After that everything works well. Thanks for help 👍
